<?php

return [
    'en' => [
        'meta_title_suffix' => 'Filipino food, delivered',
        'skip_to_content' => 'Skip to content',
        'nav_main' => 'Main',
        'nav_account' => 'Account',
        'nav_open_menu' => 'Toggle menu',
        'language' => 'Language',
        'nav_home' => 'Home', 'nav_menu' => 'Menu', 'nav_orders' => 'My orders',
        'nav_favorites' => 'Favorites', 'nav_wishlist' => 'Wishlist', 'nav_profile' => 'Profile',
        'nav_login' => 'Log in', 'nav_register' => 'Sign up', 'nav_logout' => 'Log out', 'nav_admin' => 'Admin',
        'hero_cta' => 'Order now', 'hero_view_menu' => 'Browse the menu',
        'hero_fee' => 'Delivery fee %s per order',
        'hero_pick' => 'Diner favorite',
        'section_featured' => 'Featured dishes', 'section_popular' => 'Ordered often',
        'section_categories' => 'Browse by category', 'section_reviews' => 'Recent reviews',
        'view_all' => 'See full menu',
        'about_title' => 'Our story',
        'about_body' => 'Basta Masarap started as a small carinderia with one promise: real Filipino home cooking, made with care and served without fuss. Every dish on the menu is a recipe that was passed down, refined, and made for sharing.',
        'review_on' => 'on %s',
        'search_label' => 'Search dishes', 'search_placeholder' => 'Search by name or ingredient',
        'sort_label' => 'Sort by', 'all_categories' => 'All',
        'sort_popular' => 'Most popular', 'sort_price_low' => 'Price: low to high', 'sort_price_high' => 'Price: high to low', 'sort_rating' => 'Highest rated', 'sort_newest' => 'Newest',
        'results_one' => '1 dish', 'results_many' => '%d dishes',
        'menu_sub' => 'Everything is cooked to order.',
        'no_results_title' => 'No dishes match that search',
        'no_results_text' => 'Try a different word, or clear the filters to see the whole menu.',
        'clear_filters' => 'Clear filters',
        'add' => 'Add', 'added' => 'Added', 'add_to_cart' => 'Add to cart', 'view_details' => 'View details',
        'unavailable' => 'Unavailable', 'sold_out_note' => 'This dish is not available right now.',
        'badge_popular' => 'Popular', 'badge_featured' => 'Featured',
        'rating_none' => 'No reviews yet', 'rating_aria' => 'Rated %s out of 5 from %d reviews',
        'like' => 'Like', 'dislike' => 'Dislike',
        'add_favorite' => 'Add to favorites', 'remove_favorite' => 'Remove from favorites',
        'add_wishlist' => 'Save to wishlist', 'remove_wishlist' => 'Remove from wishlist',
        'ingredients' => 'Ingredients', 'edited' => 'edited',
        'reviews' => 'Reviews', 'write_review' => 'Write a review', 'edit_review' => 'Edit your review',
        'your_review' => 'Your review', 'your_rating' => 'Your rating', 'rating_group' => 'Rating',
        'rating_star' => '%d out of 5', 'comment' => 'Comment', 'comment_placeholder' => 'What did you think of it?',
        'submit_review' => 'Post review', 'save_review' => 'Save changes', 'delete_review' => 'Delete',
        'delete_review_confirm' => 'Delete your review?', 'report' => 'Report', 'reported' => 'Reported',
        'no_reviews' => 'No reviews yet. Be the first to say something.',
        'review_hidden_note' => 'The restaurant has hidden this review, so only you can see it.',
        'login_to_review' => 'Log in to write a review.',
        'cart_title' => 'Your cart', 'nav_cart' => 'Cart', 'edit_cart' => 'Edit cart', 'item_one' => '1 item', 'item_many' => '%d items', 'cart_bar_view' => 'View cart',
        'cart_empty' => 'Your cart is empty', 'cart_empty_text' => 'Add a dish from the menu and it will show up here.',
        'subtotal' => 'Subtotal', 'delivery_fee' => 'Delivery fee', 'total' => 'Total',
        'checkout' => 'Continue to checkout', 'continue_shopping' => 'Keep browsing', 'remove' => 'Remove',
        'remove_item' => 'Remove %s', 'qty_decrease' => 'Decrease quantity', 'qty_increase' => 'Increase quantity', 'each' => '%s each',
        'cart_unavailable_line' => 'No longer available. Remove it to continue.',
        'cart_unavailable_notice' => 'Some dishes are no longer available. Remove them to check out.',
        'checkout_title' => 'Checkout', 'checkout_sub' => 'Tell us where to bring your order.',
        'delivery_address' => 'Delivery address', 'address_hint' => 'House or unit number, street, barangay, city.',
        'contact_number' => 'Contact number', 'contact_hint' => 'The rider will call this number.',
        'place_order' => 'Place order', 'pay_note' => 'Payment is collected on delivery.',
        'order_placed_title' => 'Order placed', 'order_placed_text' => 'We received your order %s and will confirm it shortly.',
        'order_id' => 'Order', 'delivery_id' => 'Delivery', 'order_history' => 'My orders', 'order_history_sub' => 'Track current orders and reorder past favorites.',
        'placed_on' => 'Placed %s', 'deliver_to' => 'Deliver to', 'reorder' => 'Order again', 'cancel_order' => 'Cancel order',
        'cancel_order_confirm' => 'Cancel this order? This cannot be undone.', 'order_cancelled' => 'Order cancelled.',
        'order_cannot_cancel' => 'This order can no longer be cancelled.',
        'reorder_done' => 'Added the available dishes to your cart.', 'reorder_none' => 'None of those dishes are available right now.',
        'no_orders' => 'No orders yet', 'no_orders_text' => 'When you place an order, you can follow it here.',
        'items' => 'Items', 'qty' => 'Qty',
        'status_pending' => 'Received', 'status_confirmed' => 'Confirmed', 'status_preparing' => 'Preparing',
        'status_out_for_delivery' => 'On the way', 'status_delivered' => 'Delivered', 'status_cancelled' => 'Cancelled',
        'login_title' => 'Log in', 'login_sub' => 'Welcome back. Pick up where you left off.',
        'username_or_email' => 'Username or email', 'password' => 'Password', 'no_account' => 'New here?',
        'register_title' => 'Create an account', 'register_sub' => 'It takes a minute and lets you order, save dishes, and leave reviews.',
        'full_name' => 'Full name', 'username' => 'Username', 'username_hint' => '3 to 30 letters, numbers, or underscores.',
        'email' => 'Email', 'confirm_password' => 'Confirm password', 'password_hint' => 'At least %d characters.',
        'already_have_account' => 'Already have an account?',
        'account_created' => 'Account created. You can log in now.', 'logged_out' => 'You have been logged out.',
        'profile_title' => 'Profile', 'profile_sub' => 'Your details are used to pre-fill checkout.',
        'member_since' => 'Member since %s', 'save_changes' => 'Save changes', 'profile_saved' => 'Profile saved.',
        'change_password' => 'Change password', 'current_password' => 'Current password', 'new_password' => 'New password',
        'password_changed' => 'Password changed.', 'err_current_password' => 'Your current password is incorrect.',
        'my_reviews' => 'My reviews', 'no_my_reviews' => 'You have not reviewed any dishes yet.',
        'favorites_title' => 'Favorites', 'favorites_sub' => 'Dishes you love and want to find again.',
        'wishlist_title' => 'Wishlist', 'wishlist_sub' => 'Dishes you want to try later.',
        'no_favorites' => 'No favorites yet', 'no_favorites_text' => 'Tap the heart on any dish to keep it here.',
        'no_wishlist' => 'Your wishlist is empty', 'no_wishlist_text' => 'Tap the bookmark on any dish you want to try later.',
        'optional' => '(optional)', 'cancel' => 'Cancel', 'confirm' => 'Confirm', 'working' => 'Working',
        'pagination' => 'Pagination', 'previous' => 'Previous', 'next' => 'Next', 'page_of' => 'Page %d of %d',
        'time_now' => 'just now', 'time_minutes' => '%d min ago', 'time_hours' => '%d h ago', 'time_days' => '%d d ago',
        'footer_tagline' => 'Real Filipino food, cooked with care.', 'footer_contact' => 'Find us', 'footer_menu' => 'Menu categories',
        'footer_rights' => 'All rights reserved.',
        'err_server' => 'Something went wrong on our side. Please try again.',
        'err_500_title' => 'Something went wrong', 'err_500_text' => 'We could not load this page. Try again in a moment.',
        'err_unavailable_title' => 'We are temporarily offline', 'err_unavailable_text' => 'The ordering system is not reachable right now. Please try again in a few minutes.',
        'err_403_title' => 'You cannot open this page', 'err_403_text' => 'This page is for administrators only.',
        'err_404_title' => 'Page not found', 'err_404_text' => 'That page does not exist or has been moved.',
        'err_dish_missing_title' => 'Dish not found', 'err_dish_missing_text' => 'This dish is no longer on the menu.',
        'err_csrf' => 'Your session expired. Please reload the page and try again.',
        'err_csrf_form' => 'Your session expired. Please try again.',
        'err_login_invalid' => 'That username, email, or password is not right.',
        'err_login_inactive' => 'This account has been deactivated. Contact the restaurant for help.',
        'err_login_throttled' => 'Too many failed attempts. Wait %d minutes and try again.',
        'err_required' => 'Please fill in all required fields.',
        'err_email' => 'Enter a valid email address.',
        'err_username' => 'Username must be 3 to 30 letters, numbers, or underscores.',
        'err_password_short' => 'Password must be at least %d characters.',
        'err_password_long' => 'Password can be at most %d characters.',
        'err_password_match' => 'The two passwords do not match.',
        'err_taken' => 'That username or email is already registered.',
        'err_email_taken' => 'That email is already used by another account.',
        'err_phone' => 'Enter a valid phone number, for example 0917 123 4567.',
        'err_address' => 'Enter a delivery address of at least 10 characters.',
        'err_cart_empty' => 'Your cart has no available dishes.',
        'err_checkout' => 'We could not place your order. Please try again.',
        'err_login_required' => 'Log in to do that.',
        'err_invalid' => 'That request was not valid.',
        'err_dish_gone' => 'That dish is not on the menu.',
        'err_dish_off' => 'This dish is unavailable right now.',
        'err_cart_max' => 'You can order up to %d of one dish.',
        'err_cart_lines' => 'Your cart is full. Remove something to add more.',
        'err_review_fields' => 'Add a rating and a comment.',
        'err_review_long' => 'Keep your review under 1000 characters.',
        'err_review_dupe' => 'You already reviewed this dish.',
        'err_review_missing' => 'That review could not be found.',
        'err_report_own' => 'You cannot report your own review.',
        'msg_review_posted' => 'Review posted. Salamat!', 'msg_review_updated' => 'Review updated.', 'msg_review_deleted' => 'Review deleted.',
        'msg_reported' => 'Thanks. We will take a look.', 'msg_already_reported' => 'You already reported this review.',
        'js_network' => 'You appear to be offline. Check your connection and try again.',
        'js_required' => 'This field is required.', 'js_email' => 'Enter a valid email address.',
        'js_too_short' => 'Use at least %d characters.', 'js_mismatch' => 'The passwords do not match.',
        'js_rating' => 'Choose a rating.',
    ],
    'fil' => [
        'meta_title_suffix' => 'Pagkaing Pinoy, ide-deliver',
        'skip_to_content' => 'Lumaktaw sa nilalaman',
        'nav_main' => 'Pangunahin',
        'nav_account' => 'Account',
        'nav_open_menu' => 'Buksan o isara ang menu',
        'language' => 'Wika',
        'nav_home' => 'Home', 'nav_menu' => 'Menu', 'nav_orders' => 'Mga order ko',
        'nav_favorites' => 'Paborito', 'nav_wishlist' => 'Wishlist', 'nav_profile' => 'Profile',
        'nav_login' => 'Mag-log in', 'nav_register' => 'Mag-sign up', 'nav_logout' => 'Mag-log out', 'nav_admin' => 'Admin',
        'hero_cta' => 'Mag-order na', 'hero_view_menu' => 'Tingnan ang menu',
        'hero_fee' => 'Delivery fee na %s bawat order',
        'hero_pick' => 'Paborito ng mga kumakain',
        'section_featured' => 'Mga tampok na ulam', 'section_popular' => 'Madalas i-order',
        'section_categories' => 'Mag-browse ayon sa kategorya', 'section_reviews' => 'Mga bagong review',
        'view_all' => 'Tingnan ang buong menu',
        'about_title' => 'Ang kwento namin',
        'about_body' => 'Nagsimula ang Basta Masarap bilang maliit na carinderia na may isang pangako: totoong lutong-bahay na Pinoy, niluto nang may pag-aalaga at inihain nang walang arte. Bawat ulam sa menu ay recipe na pinasa, pinino, at para sa pagsasaluhan.',
        'review_on' => 'sa %s',
        'search_label' => 'Maghanap ng ulam', 'search_placeholder' => 'Hanapin ayon sa pangalan o sangkap',
        'sort_label' => 'Ayusin ayon sa', 'all_categories' => 'Lahat',
        'sort_popular' => 'Pinakasikat', 'sort_price_low' => 'Presyo: mura muna', 'sort_price_high' => 'Presyo: mahal muna', 'sort_rating' => 'Pinakamataas ang rating', 'sort_newest' => 'Pinakabago',
        'results_one' => '1 ulam', 'results_many' => '%d ulam',
        'menu_sub' => 'Niluluto ang lahat kapag inorder mo na.',
        'no_results_title' => 'Walang ulam na tugma sa hinanap mo',
        'no_results_text' => 'Subukan ang ibang salita, o i-clear ang filter para makita ang buong menu.',
        'clear_filters' => 'I-clear ang filter',
        'add' => 'Idagdag', 'added' => 'Naidagdag', 'add_to_cart' => 'Idagdag sa cart', 'view_details' => 'Tingnan ang detalye',
        'unavailable' => 'Walang stock', 'sold_out_note' => 'Hindi available ang ulam na ito ngayon.',
        'badge_popular' => 'Sikat', 'badge_featured' => 'Tampok',
        'rating_none' => 'Wala pang review', 'rating_aria' => 'Rating na %s sa 5 mula sa %d review',
        'like' => 'Gusto', 'dislike' => 'Ayaw',
        'add_favorite' => 'Idagdag sa paborito', 'remove_favorite' => 'Alisin sa paborito',
        'add_wishlist' => 'I-save sa wishlist', 'remove_wishlist' => 'Alisin sa wishlist',
        'ingredients' => 'Mga sangkap', 'edited' => 'na-edit',
        'reviews' => 'Mga review', 'write_review' => 'Mag-review', 'edit_review' => 'I-edit ang review mo',
        'your_review' => 'Review mo', 'your_rating' => 'Rating mo', 'rating_group' => 'Rating',
        'rating_star' => '%d sa 5', 'comment' => 'Komento', 'comment_placeholder' => 'Ano ang masasabi mo rito?',
        'submit_review' => 'I-post ang review', 'save_review' => 'I-save ang pagbabago', 'delete_review' => 'Burahin',
        'delete_review_confirm' => 'Buburahin ang review mo?', 'report' => 'I-report', 'reported' => 'Na-report',
        'no_reviews' => 'Wala pang review. Ikaw na ang mauna.',
        'review_hidden_note' => 'Itinago ng restaurant ang review na ito, kaya ikaw lang ang makakakita.',
        'login_to_review' => 'Mag-log in para mag-review.',
        'cart_title' => 'Cart mo', 'nav_cart' => 'Cart', 'edit_cart' => 'Baguhin ang cart', 'item_one' => '1 item', 'item_many' => '%d item', 'cart_bar_view' => 'Tingnan ang cart',
        'cart_empty' => 'Walang laman ang cart mo', 'cart_empty_text' => 'Magdagdag ng ulam mula sa menu at lalabas ito rito.',
        'subtotal' => 'Subtotal', 'delivery_fee' => 'Delivery fee', 'total' => 'Kabuuan',
        'checkout' => 'Ituloy sa checkout', 'continue_shopping' => 'Mag-browse pa', 'remove' => 'Alisin',
        'remove_item' => 'Alisin ang %s', 'qty_decrease' => 'Bawasan ang dami', 'qty_increase' => 'Dagdagan ang dami', 'each' => '%s bawat isa',
        'cart_unavailable_line' => 'Hindi na available. Alisin ito para makapagpatuloy.',
        'cart_unavailable_notice' => 'May mga ulam na hindi na available. Alisin ang mga ito para makapag-checkout.',
        'checkout_title' => 'Checkout', 'checkout_sub' => 'Sabihin kung saan namin dadalhin ang order mo.',
        'delivery_address' => 'Delivery address', 'address_hint' => 'Numero ng bahay o unit, kalye, barangay, lungsod.',
        'contact_number' => 'Contact number', 'contact_hint' => 'Ito ang tatawagan ng rider.',
        'place_order' => 'I-place ang order', 'pay_note' => 'Bayad pagdating ng order.',
        'order_placed_title' => 'Na-place na ang order', 'order_placed_text' => 'Natanggap namin ang order %s at kukumpirmahin namin ito agad.',
        'order_id' => 'Order', 'delivery_id' => 'Delivery', 'order_history' => 'Mga order ko', 'order_history_sub' => 'Subaybayan ang mga order at umorder ulit ng mga paborito.',
        'placed_on' => 'Na-place noong %s', 'deliver_to' => 'Ihahatid sa', 'reorder' => 'Umorder ulit', 'cancel_order' => 'Kanselahin ang order',
        'cancel_order_confirm' => 'Kakanselahin ang order na ito? Hindi na ito mababawi.', 'order_cancelled' => 'Nakansela ang order.',
        'order_cannot_cancel' => 'Hindi na maaaring kanselahin ang order na ito.',
        'reorder_done' => 'Naidagdag sa cart ang mga available na ulam.', 'reorder_none' => 'Walang available sa mga ulam na iyon ngayon.',
        'no_orders' => 'Wala ka pang order', 'no_orders_text' => 'Kapag nag-order ka, masusubaybayan mo ito rito.',
        'items' => 'Mga item', 'qty' => 'Dami',
        'status_pending' => 'Natanggap', 'status_confirmed' => 'Nakumpirma', 'status_preparing' => 'Inihahanda',
        'status_out_for_delivery' => 'Papunta na', 'status_delivered' => 'Naihatid na', 'status_cancelled' => 'Nakansela',
        'login_title' => 'Mag-log in', 'login_sub' => 'Welcome back. Ituloy natin kung saan ka huminto.',
        'username_or_email' => 'Username o email', 'password' => 'Password', 'no_account' => 'Bago ka rito?',
        'register_title' => 'Gumawa ng account', 'register_sub' => 'Isang minuto lang, at makakapag-order ka na, mag-save ng ulam, at mag-review.',
        'full_name' => 'Buong pangalan', 'username' => 'Username', 'username_hint' => '3 hanggang 30 titik, numero, o underscore.',
        'email' => 'Email', 'confirm_password' => 'Kumpirmahin ang password', 'password_hint' => 'Hindi bababa sa %d character.',
        'already_have_account' => 'May account ka na?',
        'account_created' => 'Nagawa na ang account. Maaari ka nang mag-log in.', 'logged_out' => 'Naka-log out ka na.',
        'profile_title' => 'Profile', 'profile_sub' => 'Ginagamit ang mga detalye mo para i-fill in ang checkout.',
        'member_since' => 'Miyembro mula %s', 'save_changes' => 'I-save ang pagbabago', 'profile_saved' => 'Na-save ang profile.',
        'change_password' => 'Palitan ang password', 'current_password' => 'Kasalukuyang password', 'new_password' => 'Bagong password',
        'password_changed' => 'Napalitan ang password.', 'err_current_password' => 'Mali ang kasalukuyang password mo.',
        'my_reviews' => 'Mga review ko', 'no_my_reviews' => 'Wala ka pang na-review na ulam.',
        'favorites_title' => 'Paborito', 'favorites_sub' => 'Mga ulam na gusto mo at gusto mong balikan.',
        'wishlist_title' => 'Wishlist', 'wishlist_sub' => 'Mga ulam na gusto mong subukan sa susunod.',
        'no_favorites' => 'Wala pang paborito', 'no_favorites_text' => 'I-tap ang puso sa kahit anong ulam para ilagay ito rito.',
        'no_wishlist' => 'Walang laman ang wishlist mo', 'no_wishlist_text' => 'I-tap ang bookmark sa ulam na gusto mong subukan sa susunod.',
        'optional' => '(opsyonal)', 'cancel' => 'Kanselahin', 'confirm' => 'Kumpirmahin', 'working' => 'Ginagawa',
        'pagination' => 'Mga pahina', 'previous' => 'Nakaraan', 'next' => 'Susunod', 'page_of' => 'Pahina %d ng %d',
        'time_now' => 'ngayon lang', 'time_minutes' => '%d min ang nakalipas', 'time_hours' => '%d oras ang nakalipas', 'time_days' => '%d araw ang nakalipas',
        'footer_tagline' => 'Totoong pagkaing Pinoy, niluto nang may pag-aalaga.', 'footer_contact' => 'Hanapin kami', 'footer_menu' => 'Mga kategorya ng menu',
        'footer_rights' => 'Lahat ng karapatan ay nakalaan.',
        'err_server' => 'May problema sa aming panig. Subukan ulit.',
        'err_500_title' => 'May nangyaring mali', 'err_500_text' => 'Hindi namin ma-load ang pahinang ito. Subukan ulit maya-maya.',
        'err_unavailable_title' => 'Offline kami saglit', 'err_unavailable_text' => 'Hindi maabot ang sistema ng pag-order ngayon. Subukan ulit sa loob ng ilang minuto.',
        'err_403_title' => 'Hindi mo mabubuksan ang pahinang ito', 'err_403_text' => 'Para lang sa mga administrator ang pahinang ito.',
        'err_404_title' => 'Hindi mahanap ang pahina', 'err_404_text' => 'Wala ang pahinang iyon o inilipat na.',
        'err_dish_missing_title' => 'Hindi mahanap ang ulam', 'err_dish_missing_text' => 'Wala na ang ulam na ito sa menu.',
        'err_csrf' => 'Nag-expire ang session mo. I-reload ang pahina at subukan ulit.',
        'err_csrf_form' => 'Nag-expire ang session mo. Subukan ulit.',
        'err_login_invalid' => 'Mali ang username, email, o password.',
        'err_login_inactive' => 'Na-deactivate ang account na ito. Makipag-ugnayan sa restaurant.',
        'err_login_throttled' => 'Napakaraming maling subok. Maghintay ng %d minuto at subukan ulit.',
        'err_required' => 'Punan ang lahat ng kinakailangang field.',
        'err_email' => 'Maglagay ng tamang email address.',
        'err_username' => 'Ang username ay dapat 3 hanggang 30 titik, numero, o underscore.',
        'err_password_short' => 'Dapat hindi bababa sa %d character ang password.',
        'err_password_long' => 'Hanggang %d character lang ang password.',
        'err_password_match' => 'Hindi magkatugma ang dalawang password.',
        'err_taken' => 'Gamit na ang username o email na iyon.',
        'err_email_taken' => 'Gamit na ng ibang account ang email na iyon.',
        'err_phone' => 'Maglagay ng tamang phone number, halimbawa 0917 123 4567.',
        'err_address' => 'Maglagay ng delivery address na hindi bababa sa 10 character.',
        'err_cart_empty' => 'Walang available na ulam sa cart mo.',
        'err_checkout' => 'Hindi namin na-place ang order mo. Subukan ulit.',
        'err_login_required' => 'Mag-log in para magawa iyon.',
        'err_invalid' => 'Hindi valid ang request na iyon.',
        'err_dish_gone' => 'Wala sa menu ang ulam na iyon.',
        'err_dish_off' => 'Hindi available ang ulam na ito ngayon.',
        'err_cart_max' => 'Hanggang %d lang ng bawat ulam ang maiu-order.',
        'err_cart_lines' => 'Puno na ang cart mo. Mag-alis muna para makapagdagdag.',
        'err_review_fields' => 'Maglagay ng rating at komento.',
        'err_review_long' => 'Panatilihing wala pang 1000 character ang review.',
        'err_review_dupe' => 'Na-review mo na ang ulam na ito.',
        'err_review_missing' => 'Hindi mahanap ang review na iyon.',
        'err_report_own' => 'Hindi mo maaaring i-report ang sarili mong review.',
        'msg_review_posted' => 'Na-post ang review. Salamat!', 'msg_review_updated' => 'Na-update ang review.', 'msg_review_deleted' => 'Nabura ang review.',
        'msg_reported' => 'Salamat. Titingnan namin ito.', 'msg_already_reported' => 'Na-report mo na ang review na ito.',
        'js_network' => 'Mukhang offline ka. Tingnan ang koneksyon at subukan ulit.',
        'js_required' => 'Kinakailangan ang field na ito.', 'js_email' => 'Maglagay ng tamang email address.',
        'js_too_short' => 'Gumamit ng hindi bababa sa %d character.', 'js_mismatch' => 'Hindi magkatugma ang mga password.',
        'js_rating' => 'Pumili ng rating.',
    ],
];
